kind: Pod
apiVersion: v1
metadata:
  name: env 
spec:
  containers:
  - name: nginx
    image: nginx
    env:
    - name: course
      value: "DevSecOps"
    - name: trainer
      value: "SivaKumar M"
    - name: duration
      value: "120HRS"
      